Config file for st7789 (waveshare hat version)
rm-hull/luma.examples pull request #143
Opened 2021-03-14 18:43 UTC by matemaciek

2021-03-14 21:09 UTC, iceman1001 commented
```pi@raspberrypi:~/luma.examples/examples $ python3 bounce.py --display=st7789
Traceback (most recent call last):
  File "bounce.py", line 80, in <module>
    device = get_device()
  File "/home/pi/luma.examples/examples/demo_opts.py", line 63, in get_device
    device = cmdline.create_device(args)
  File "/usr/local/lib/python3.7/dist-packages/luma/core/cmdline.py", line 252, in create_device
    backlight_params = dict(gpio=interface.gpio, gpio_LIGHT=args.gpio_backlight, active_low=args.backlight_active == "low")
AttributeError: 'i2c' object has no attribute 'gpio'
```
When I try your conf,  luma.core seem to want to do a GPIO for lcd,

2021-03-14 21:23 UTC, thijstriemstra requested changes

2021-03-14 21:23 UTC, thijstriemstra commented on conf/sh1106.conf
> +--interface=spi
not sure about that one. can you rename it to ssh1106-waveshare.conf?

2021-03-14 21:30 UTC, matemaciek commented
> ```
> Traceback (most recent call last):
>   File "bounce.py", line 80, in <module>
>     device = get_device()
>   File "/home/pi/luma.examples/examples/demo_opts.py", line 63, in get_device
>     device = cmdline.create_device(args)
>   File "/usr/local/lib/python3.7/dist-packages/luma/core/cmdline.py", line 252, in create_device
>     backlight_params = dict(gpio=interface.gpio, gpio_LIGHT=args.gpio_backlight, active_low=args.backlight_active == "low")
> AttributeError: 'i2c' object has no attribute 'gpio'
> ```
> 
> When I try your conf, luma.core seem to want to do a GPIO for lcd,

Can you share command you're running?

2021-03-14 22:02 UTC, iceman1001 commented
```
python3 bounce.py -i spi -d st7789 --gpio-reset 27 --gpio-data-command 25 --gpio-backlight 24 --backlight-active high --spi-bus-speed 52000000
```

2021-03-15 12:45 UTC, iceman1001 commented
I had uninstall / install  core, oled, lcd,  examples,   and now it works :)

2021-06-25 16:52 UTC, thijstriemstra approved these changes

2021-06-25 16:55 UTC, merged